Repository KonferCA/HawkHacks-Dashboard, pull requests merged in 2024-04, with the labels that each got.

#74 [Feature] Implement side navbar
  package.json
  pnpm-lock.yaml
  src/assets/hh-dashboard-logo.svg
  src/components/Navbar.tsx
  src/components/PageWrapper/PageWrapper.tsx
  src/components/index.tsx
  src/pages/user/User.page.tsx
Labels: enhancement

#82 Bug/80/login-page-not-responsive
  src/pages/Login/Login.page.tsx
Labels: bug

#83 Application Form
  .eslintrc.cjs
  config/firestore.rules
  package.json
  pnpm-lock.yaml
  src/components/Button/Button.tsx
  src/components/Button/Button.type.ts
  src/components/LoadingAnimation.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/Navbar.tsx
  src/components/PageWrapper/PageWrapper.tsx
  src/components/Select/Select.test.tsx
  src/components/Select/Select.tsx
  src/components/Steps/Steps.tsx
  src/components/TextInput/TextInput.tsx
  src/components/common.ts
  src/components/forms/Profile.tsx
  src/components/forms/defaults.ts
  src/components/forms/hackerApplication.ts
  src/components/forms/types.ts
  src/components/forms/validations.ts
  src/components/index.tsx
  src/components/types.ts
  src/data/ages.ts
  src/data/index.ts
  src/data/levelsOfStudy.ts
  src/data/schools.ts
  src/main.tsx
  src/navigation/ProtectedRoutes/ProtectedRoutes.test.tsx
  src/navigation/ProtectedRoutes/ProtectedRoutes.tsx
  src/navigation/Router.tsx
  src/navigation/constants.ts
  src/navigation/index.tsx
  src/pages/Application/Application.page.tsx
  src/pages/Login/Login.page.tsx
  src/pages/admin/Admin.page.tsx
  src/pages/index.tsx
  src/pages/miscellaneous/VerifyEmail.page.tsx
  src/pages/user/CompleteProfile.page.tsx
  src/pages/user/User.page.tsx
  src/providers/auth.provider.tsx
  src/providers/hooks.ts
  src/providers/index.tsx
  src/providers/notification.provider.tsx
  src/providers/types.ts
  src/services/index.ts
  src/services/utils/index.ts
  src/services/utils/types.ts
  src/utils/Router.tsx
  src/utils/index.tsx
  src/utils/testUtils.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#88 add loading animation to application page
  src/pages/Application/Application.page.tsx
Labels: enhancement

#95 update firebase hosting config -- rewrite paths
  firebase.json
Labels: bug

#97 Bug/96/login-enter-password-reset-issue
  src/pages/Login/Login.page.tsx
Labels: bug

#103 102 bug fix security vulneratibilites
  config/firestore.rules
  functions/package.json
  functions/pnpm-lock.yaml
  functions/src/data.ts
  functions/src/index.ts
  src/components/forms/Profile.tsx
  src/components/forms/defaults.ts
  src/components/forms/validations.ts
  src/main.tsx
  src/pages/Application/Application.page.tsx
  src/pages/Login/Login.page.tsx
  src/pages/user/CompleteProfile.page.tsx
  src/services/utils/index.ts
  src/services/utils/types.ts
Labels: bug

#156 Fix: change "Asian Indian" to "South Asian / Asian Indian"
  src/data/index.ts
Labels: bug

#155 Fix: prioritise Canada and the USA at the top of countryNames list
  src/data/countryNames.ts
Labels: bug

#158 feature/142/url opens in new tab
  src/pages/Application/Application.page.tsx
Labels: feature

#119 New Form Questions + Format
  functions/src/index.ts
  src/components/MultiSelect/MultiSelect.tsx
  src/components/Select/Select.tsx
  src/components/TextArea/TextArea.tsx
  src/components/forms/Profile.tsx
  src/components/forms/defaults.ts
  src/components/forms/hackerApplication.ts
  src/components/forms/types.ts
  src/components/forms/validations.ts
  src/data/cities.ts
  src/data/index.ts
  src/data/levelsOfStudy.ts
  src/pages/Application/Application.page.tsx
  src/services/utils/types.ts
Labels: feature

#154 Phone input
  src/components/PhoneInput/PhoneInput.tsx
  src/components/forms/Profile.tsx
  src/components/index.tsx
  src/data/countryPhoneCodes.ts
Labels: feature

#177 remove duplicate waterloo entry in cities
  src/data/cities.ts
Labels: bug

#176 Add resume upload
  config/storage.rules
  src/components/FileBrowse/FileBrowse.tsx
  src/components/forms/Profile.tsx
  src/components/forms/defaults.ts
  src/components/forms/types.ts
  src/components/forms/validations.ts
  src/pages/Application/Application.page.tsx
  src/services/firebase.ts
  src/services/utils/index.ts
Labels: feature

#214 add basic event logs for services
  functions/src/index.ts
  src/services/utils/index.ts
Labels: URGENT, important

#225 218 setup local emulators for local development
  config/firestore.rules
  config/storage.rules
  package.json
  pnpm-lock.yaml
  src/services/firebase.ts
Labels: feature, URGENT, important

#227 AppCheck / ReCaptcha V3
  src/services/firebase.ts
  src/vite-env.d.ts
Labels: URGENT, important

#232 Prod Deployments For AppCheck/ReCaptcha
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  config/storage.rules
  firebase.json
  index.html
  src/services/firebase.ts
  src/vite-env.d.ts
Labels: deployment

#226 add application progress tracking
  src/pages/Application/Application.page.tsx
Labels: URGENT

#237 Discord Support Elements
  src/components/Navbar.tsx
  src/components/PageWrapper/PageWrapper.tsx
Labels: URGENT
