Repository KonferCA/HawkHacks-Dashboard, pull requests merged in 2025-05, with the labels that each got.

#512 updated navbar
  src/components/Navbar.tsx
Labels: frontend, enhancement

#541 removed welcome msg
  src/components/Navbar.tsx
Labels: frontend, enhancement

#507 Update infoCallout component to use Chakra Alert
  pnpm-lock.yaml
  src/components/InfoCallout/InfoCallout.tsx
Labels: frontend, enhancement

#543 Update firestore.rules
  config/firestore.rules
Labels: backend, enhancement

#503 fixes dark mode bug
  src/components/ui/color-mode.tsx
Labels: bug, frontend

#544 Add firebase hosting deploy on PR
  .github/workflows/firebase-hosting-merge-dev.yml
Labels: pipeline, enhancement

#550 Make schedule responsive, add line for current time
  biome.json
  src/components/PageWrapper/PageWrapper.tsx
  src/components/Schedule/Schedule.tsx
  src/pages/Schedule/schedule.page.tsx
Labels: frontend, enhancement

#551 Add event details modal to schedule
  src/components/Schedule/Schedule.tsx
  src/pages/Schedule/schedule.page.tsx
Labels: frontend, enhancement

#552 Add admin QR code scan page
  .github/workflows/code-quality.yml
  .github/workflows/firebase-hosting-merge-dev.yml
  docs/CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  src/components/Scanner/QRCodeScanner.tsx
  src/components/Scanner/VideoInputDeviceSelector.tsx
  src/hooks/use-document-visibility.ts
  src/hooks/use-qr-code-reader.ts
  src/pages/admin/AdminScan.page.tsx
  src/providers/RoutesProvider/RoutesProvider.tsx
  src/providers/RoutesProvider/data.ts
  src/providers/RoutesProvider/types.ts
  src/services/firebase/index.ts
Labels: frontend, enhancement

#546 Enhancement/user roles/516
  data/auth_export/accounts.json
  data/firebase-export-metadata.json
  data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  data/firestore_export/all_namespaces/all_kinds/output-0
  data/storage_export/blobs/67c80d93-8cea-4b51-933c-afc503c566e2
  data/storage_export/blobs/cd21dc0e-b897-4864-a73d-2011e978ae43
  data/storage_export/metadata/67c80d93-8cea-4b51-933c-afc503c566e2.json
  data/storage_export/metadata/cd21dc0e-b897-4864-a73d-2011e978ae43.json
  src/providers/AuthProvider/hooks.ts
  src/providers/AuthProvider/index.ts
  src/providers/AuthProvider/types.ts
  src/providers/AuthProvider/utils.ts
  src/providers/index.tsx
Labels: frontend, enhancement
