Repository KonferCA/HawkHacks-Dashboard, pull requests merged in 2025-04, with the labels that each got.

#466 Move usages of `process.env` within functions
  functions/src/rsvp.ts
  package.json
Labels: bug, backend

#464 Migrate from `useNotification` to chakra ui toaster
  src/components/Application.tsx
  src/components/Notification/Notification.test.tsx
  src/components/Notification/Notification.tsx
  src/components/index.tsx
  src/components/types.ts
  src/main.tsx
  src/pages/Application/Application.page.tsx
  src/pages/Home/Home.page.tsx
  src/pages/JoinTeam.page.tsx
  src/pages/MyTeam.page.tsx
  src/pages/Networking/Networking.page.tsx
  src/pages/admin/ManageEvents.page.tsx
  src/pages/admin/ViewTicket.page.tsx
  src/pages/miscellaneous/VerifyRSVP.page.tsx
  src/pages/miscellaneous/ViewTicket.page.tsx
  src/providers/auth.provider.tsx
  src/providers/hooks.ts
  src/providers/index.tsx
  src/providers/notification.provider.tsx
  src/providers/types.ts
Labels: refactor, frontend

#468 Update TextArea.tsx
  src/components/TextArea/TextArea.tsx
Labels: enhancement

#467 Port Button component to Chakra UI
  src/components/Button/Button.tsx
Labels: enhancement
